### ISSUE TITLE
what if I use retriv in a developing environment without any network（such as a docker container）

### ISSUE THREAD

**Issue by skykiseki** [AmenRa/retriv#10]
have  a good experience at using retriv ,

but nltk will download some files when users start to use the package, this means that users developing in offline enviroment can't use it at all.

I think let users to define dicts for their own usage is more people-friendly.

**Comment by AmenRa** [comment]
Hi and thanks for the kind word!

I understand your needs and thank you for let me know about that.
I will make the download of additional data triggered when requested the first time instead that on `retriv` loading.
Note that you can already define your stop-words bypassing NLTK, for example.

**Comment by AmenRa** [comment]
Hi, I addressed the issue in `v.0.2.0`.
Let me know if the changes solved it.
Thank you!

**Comment by skykiseki** [comment]
> Hi, I addressed the issue in `v.0.2.0`. Let me know if the changes solved it. Thank you!

That's great. I'll try it right away and wait for my feedback

**Comment by skykiseki** [comment]
v0.2.0 is more efficient to users and the above problems  have been solved，no problems have been found so far. Nice work!!!!

**Comment by skykiseki** [comment]
everything is ok

**Comment by AmenRa** [comment]
Sounds great! :)

**Comment by tshu-w** [comment]
> I understand your needs and thank you for let me know about that.
> I will make the download of additional data triggered when requested the first time instead that on `retriv` loading.

I think we should only try to download in case of a LookupError (nltk.data.find), otherwise, there will still be issues using it offline even if it has already been downloaded.
