### ISSUE TITLE
Doc strings

### ISSUE THREAD

**Issue by Alex-S-H-P** [AmenRa/retriv#17]
Hi, I can't help but notice that this codebase is quite missing in doc strings.

This really hinders my experience as someone trying to use it. In particular, auto completion does not work.
I know that you've made your documentation on markdown files, and why not, but it does not explain every function that I may want to use.

Is there an ETA on getting those ?

**Comment by AmenRa** [comment]
Hi, sorry for that.
I will add them in the coming days and keep you up-to-date.

**Comment by AmenRa** [comment]
Never mind, I've already added them.

Please, update your installation to version `0.2.1`.

Let me know if they are good enough!
Comments and suggestions are more than welcome.

Please consider giving a star to `retriv` if you like it.

**Comment by Alex-S-H-P** [comment]
This is indeed far better. I will test out the new version soon, but thanks for being so reactive !

**Comment by AmenRa** [comment]
Thank you for bringing it to my attention! :)
