### ISSUE TITLE
[Issue] Remove CyHunSpell as Required Dependency

### ISSUE THREAD

**Issue by hockyy** [AmenRa/retriv#2]
CyHunSpell can't be installed in non-debian based Linux.

**Comment by AmenRa** [comment]
I will look into it.

**Comment by aryopg** [comment]
Any update on this issue? I'm having the same problem using an M1 machine

**Comment by AmenRa** [comment]
Hi @hockyy and @aryopg,
I removed the dependence from Hunspell completely in `v0.2.0`.
I also added several new features. Please, take a look.
Feedback is welcome!
