### ISSUE TITLE
Input file format

### ISSUE THREAD

**Issue by tingliu2018** [AmenRa/retriv#21]
Hi, I'm pretty new to this. Can you give an example what a input file in jsonl format looks like?

**Comment by AmenRa** [comment]
Hi, a `JSONl` file is a file where each lines is a `JSON`.

A `collection.jsonl` file looks like this:
```json
{"id": "doc_1", "text": "Generals gathered in their masses"}
{"id": "doc_2", "text": "Just like witches at black masses"}
{"id": "doc_3", "text": "Evil minds that plot destruction"}
{"id": "doc_4", "text": "Sorcerer of death's construction"}
```

You can find more info on `JSONl` formatting [here](https://jsonlines.org), if needed.

Let me know if you need further help. :)
