### ISSUE TITLE
[BUG] Corrupted log when using SearchEngine

### ISSUE THREAD

**Issue by Ch41r05** [AmenRa/retriv#24]
Hi again,

I'm stuck with a strange behavior, that from my tests seems to be related to the use of the SearchEngine.
I'm using a SingletonLogger that logs everything to stdout and persists that log onto a file.
When the program runs, the index takes a bit of time to be calculated and if I check the logfile, I can correctly see everything printed until this point. After the SearchEngine finishes calculating the index, the first row of the logfile becomes a series of nul values.
Below a sample of code and of the log file.
Can anyone give me pointers to solve this?

```
_logger = Logger()

[code doing stuff, collecting collection mainly]

_logger.info("Building index...")
SearchEngine("new-index").index(collection, show_progress=False)
_logger.info("Index built.")
```

[logfile.log](https://github.com/AmenRa/retriv/files/12466670/logfile.log)

**Comment by Ch41r05** [comment]
Hi @AmenRa ,

Here is a script that reproduces the error. The logger class only has this problem when SearchEngine().index() is run, if commented the logs are correctly printed.

I may have done something wrong, but I can't seem to find the cause for this since every other test I've run didn't reproduce the issue.

[binary_log.zip](https://github.com/AmenRa/retriv/files/12473401/binary_log.zip)

**Comment by AmenRa** [comment]
Hi, i removed `from commons.logger import Logger`.

Everything seems to work fine on my end.
I get this in both my terminal and the log file:
```python 
[2023-09-02 09:16:28,031] {binary_log.py:55} INFO - Building index...
[2023-09-02 09:16:28,303] {binary_log.py:57} INFO - Index built.
```

**Comment by Ch41r05** [comment]
Is that what is present in the log file? The commons.logger was just the Logger class implementing a singleton, I'll upload the script using that class. I'll also try to see if the issue is present without importing the commons. Thanks for now.

**Comment by Ch41r05** [comment]
Hi @AmenRa I did some further testing and I found something interesting. If I change the order of the lines

`logger.info("Building index...")
 SearchEngine("new-index").index(collection, show_progress=False)
 logger.info("Index built.")
`

to

`logger.info("Building index...")
 logger.info("Index built.")
 SearchEngine("new-index").index(collection, show_progress=False)`

the log file becomes empty. So it seems from the tests I conducted that somehow rertiv is still sending something to stdout even when with show_progress=False. If I comment the indexing line, the log correctly is shown in the file. I'm running on windows 11 with python 3.10.0. I don't know if I can give you any more information, but please tell me if you need something else to try to reproduce the error in your environment.

**Comment by Ch41r05** [comment]
Hi @AmenRa , thanks for your help! I ran the sample code you provided me, sadly (?) everything worked fine, the output was the expected one in both the console and the logfile. Seems tqdm isn't the culprit here. I agree that the problem may lie in the fact that I'm using Windows. As I was saying this kind of behavior seems to be linked on how files are opened under the hood. I'll try to dig deeper and keep you updated if I find anything interesting, since this behavior is strange and not as intended I guess!
