### ISSUE TITLE
[Feature Request] Show progress status when performing `msearch` or `bsearch`

### ISSUE THREAD

**Issue by celsofranssa** [AmenRa/retriv#4]
Hello, I am having a good experience with `retriv` :-)
Is there an approach to add progress status when performing `msearch` or `bsearch`?

**Comment by AmenRa** [comment]
Hi, it should already be there for the `bsearch`. Is it not working?

Unfortunately, adding a progress bar to the `msearch` is not straightforward because everything happens outside of Python at run time.

**Comment by celsofranssa** [comment]
I see. I've only tested `Multi-search`. However, I'll apply `Batch-search` since I am working with hundreds of thousands of queries.
